### ISSUE TITLE
Update python loader system encoding

### ISSUE THREAD

**Issue by thomas-hervey** [openeventdata/es-geonames#14]
When running the script from scratch, I receive an encoding issue (which may not be just on my end). As a result, data isn't loaded into Elasticsearch. Adding the following to *geonames_elasticsearch_loader.py* fixed this issue for me.

```python
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```

**Comment by ahalterman** [comment]
Does it fail to run the script with an encoding error? Or does it run and then just not load anything into ES? I think I’ve only used it with Python 3.

**Comment by thomas-hervey** [comment]
It was failing saying that there is an encoding error and that all the indexed documents are an exception. However, I have been switching my environment, and perhaps I got the issue because I wasn't running the script with Python 3...
