### ISSUE TITLE
Postcodes are missing

### ISSUE THREAD

**Issue by jdomag** [openeventdata/es-geonames#16]
Hi Guys, 
I've just imported the ES index by create_index.sh however i see the postcodes are missing in the datafile that script fetches:
http://download.geonames.org/export/dump/allCountries.zip

I find out that there is a separate file with postcodes:
http://download.geonames.org/export/zip/

Is this not downloaded / supported by create_index.sh for any particular reason or it wasn't just added yet to the index?

Thanks for support!

**Comment by ahalterman** [comment]
I never had a need for postcodes in my own projects so I didn't add them to the index. I'd happily accept a PR with code that adds them in, though!
