### ISSUE TITLE
Portability issues

### ISSUE THREAD

**Issue by vks** [openeventdata/es-geonames#17]
There are two portability issues with the script generating the elasticsearch index:
* `sys.maxsize` is `2**63 - 1` on 64-bit systems, which usually does not fit into a C `long`, making the script crash on such systems.
* The encoding of the geonames file is not specified (it's UTF-8), and therefore wrong on any host system which defaults to a non-UTF-8 encoding.

I fixed both issues in my [fork](https://github.com/vks/es-geonames). If there is interest, I can create a pull request.

**Comment by ahalterman** [comment]
I think this should be fixed by @ginofft's PR #20. If it's not, please re-open!
