### ISSUE TITLE
Persistent ES index in data volume

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/es-geonames#2]
While most people will want to pull a pre-built image, some people might want to build their own (if they need frequent updates, say). The current image pulled a pre-built ES index from S3, which is pretty hacky.

Is there a way to have the container build its own data volume when it first starts up (by running the [loader](https://github.com/openeventdata/es-geonames/blob/master/geonames_elasticsearch_loader.py)), and having that volume persisted when the container shuts down? And then reconnect to the volume on restart? The Python to load the gazetteer into a running ES instance works fine (I just used it locally), but the Docker integration is the harder part.

@chilland: ideas? No worries if not, I know you have other things to do.

**Comment by chilland** [comment]
I'd dump the index, host that on S3 and just use an [ES container](https://hub.docker.com/_/elasticsearch/) with the index mounted as a volume. No need for a custom geonames image. This repo then just becomes a script for doing that I guess. This image is currently massive, so either way, its a good idea to get the data out of the image.

**Comment by ahalterman** [comment]
:+1: Thanks! So the index wouldn't be in a container, it would be added just like the data in Mordecai now (`docker ... -v PATH/TO/data:/usr/src/data...`)?

I was thinking it would be cool to be able to update the volume with Geonames' daily updates [(e.g.)](http://download.geonames.org/export/dump/modifications-2016-11-28.txt) by making a call to the `es_geonames` container, but that might be stretching beyond what's useful/doable.

**Comment by chilland** [comment]
yup
> This image is configured with a volume at /usr/share/elasticsearch/data to hold the persisted index > data. Use that path if you would like to keep the data in a mounted volume:

> $ docker run -d -v "$PWD/esdata":/usr/share/elasticsearch/data elasticsearch

I think including a utility to do updates is a cool idea. I don't think persisting the data in an image is the way to do that. Can probably make something that easily does bulk uploads when needed.
