### ISSUE TITLE
Wait for container in a less crappy way

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/es-geonames#4]
Rather than just waiting for 10 seconds, actually make sure the container is up before starting to load in data. 10 seconds is too short for the first time, too long for later times.

https://github.com/openeventdata/es-geonames/blob/master/create_index.sh#L8

**Comment by taybin** [comment]
You can use a tool like this to wait for the 9200 port to become available: https://github.com/vishnubob/wait-for-it

**Comment by taybin** [comment]
This is a race condition and will probably bite you one day if elasticsearch takes longer than expected to launch.  FYI.

**Comment by ahalterman** [comment]
You're right. I'm comfortable with it for now, because (1) ES takes ~5 seconds and downloading and unzipping the gazetteer takes ~5 minutes and (2) I rebuild it rarely enough that I'm watching it through this point. That said, if you opened a PR with wait-for-it, I'd gladly merge it.
