### ISSUE TITLE
Script to update index

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/es-geonames#5]
Geonames publishes daily updates to the gazetteer. It would be nice to be able to download and update/insert just these rather than downloading the full gazetteer and rebuilding everything every time we want to update it.

Problem: it would be very easy if the Elasticsearch ID and the Geonames ID were identical. They aren't, so we'll have to do a delete-by-query and then insert.

**Comment by taybin** [comment]
You can set the id when creating the document.  It doesn't have to be created by elasticsearch and can match the geonames id.

**Comment by panchicore** [comment]
@ahalterman see the logstash PR, with it you just have to download the update file to the logstash analyzed folder and it will do the work, bear in mind field names are changed to match with ES convention.
