### ISSUE TITLE
Change `text` to `keyword` type in ES mapping?

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/es-geonames#9]
Think about changing the text fields from `text` type to `keyword`. Currently, places with common words like "South" get pulled up on unrelated queries. This would help cut down.

In this case, the `alternativenames` field should be parsed out into a list.

**Comment by ahalterman** [comment]
Actually, keep as text to preserve fuzzy matching. We can use the `"type" : "phrase"` to get more precise matches.

But the alternative names does need to be split out into an array.

**Comment by ahalterman** [comment]
Also experiment with changing the similarity metric. We don't usually care about normalization when e.g. matching against the `alternativenames` field (in fact, we generally prefer results with longer `alternativenames` fields. We can switch to a non-tf-idf normalization in the mapping file like this:

```
...
 "alternativenames" : {"type" : "text", "similarity" : "boolean"},
...
```

**Comment by hkorte** [comment]
I just noticed that you still have `"index": "not_analyzed"` in your text fields. This contradicts your text-type. Also, `index` is actually a boolean field in Elasticsearch 5 mappings.

**Comment by ahalterman** [comment]
Thanks! I definitely don't want the fields that are currently `"index" : "not_analyzed"` to be full text searched (you can imagine how the timezone field is especially bad for this). But you're right, these should be `{"type" : "keyword", "index" : "true"}`. I'll updated this when I rebuild the index with the updated Geonames dump in a couple days.
